const HUNGARY_CITY_COUNTIES: Record<string, string> = {
  budapest: "Pest",
  debrecen: "Hajdú-Bihar",
  szeged: "Csongrád-Csanád",
  miskolc: "Borsod-Abaúj-Zemplén",
  pecs: "Baranya",
  gyor: "Győr-Moson-Sopron",
  nyiregyhaza: "Szabolcs-Szatmár-Bereg",
  kecskemet: "Bács-Kiskun",
  szekesfehervar: "Fejér",
  szombathely: "Vas",
  szolnok: "Jász-Nagykun-Szolnok",
  erd: "Pest",
  tatabanya: "Komárom-Esztergom",
  sopron: "Győr-Moson-Sopron",
  kaposvar: "Somogy",
  veszprem: "Veszprém",
  bekescsaba: "Békés",
  zalaegerszeg: "Zala",
  eger: "Heves",
  nagykanizsa: "Zala",
  dunakeszi: "Pest",
  dunaujvaros: "Fejér",
  hodmezovasarhely: "Csongrád-Csanád",
  szigetszentmiklos: "Pest",
  cegled: "Pest",
  mosonmagyarovar: "Győr-Moson-Sopron",
  baja: "Bács-Kiskun",
  vac: "Pest",
  salgotarjan: "Nógrád",
  godollo: "Pest",
  ozd: "Borsod-Abaúj-Zemplén",
  szekszard: "Tolna",
  papa: "Veszprém",
  hajduboszormeny: "Hajdú-Bihar",
  kiskunfelegyhaza: "Bács-Kiskun",
  budaors: "Pest",
  gyongyos: "Heves",
  gyula: "Békés",
  esztergom: "Komárom-Esztergom",
  ajka: "Veszprém",
  szentendre: "Pest",
  jaszbereny: "Jász-Nagykun-Szolnok",
  oroshaza: "Békés",
  kiskunhalas: "Bács-Kiskun",
  szentes: "Csongrád-Csanád",
  siofok: "Somogy",
  kazincbarcika: "Borsod-Abaúj-Zemplén",
  gyal: "Pest",
  hajduszoboszlo: "Hajdú-Bihar",
  nagykoros: "Pest",
};

export function getHungaroMetCountyForCity(citySlug: string | undefined) {
  if (!citySlug) return null;
  return HUNGARY_CITY_COUNTIES[citySlug] ?? null;
}
