project_id = "xdysdmtwhhnkvdbaaflm"

[functions.contact-form]
verify_jwt = false

[functions.generate-news]
verify_jwt = false

[functions.telegram-forecast]
verify_jwt = false

[functions.refresh-space-weather]
verify_jwt = false
